//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgetHub_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributors
    {
        public int DistributorID { get; set; }
        public string DistributorName { get; set; }
        public string DistributorEmail { get; set; }
        public string Password { get; set; }
        public string DistributorPhone { get; set; }
        public string Location { get; set; }
    }
}
