//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgetHub_Server.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GadgetHub_dbEntities3 : DbContext
    {
        public GadgetHub_dbEntities3()
            : base("name=GadgetHub_dbEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Distributors> Distributors { get; set; }
        public virtual DbSet<OrderRequests> OrderRequests { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<QuotationRequests> QuotationRequests { get; set; }
        public virtual DbSet<Quotations> Quotations { get; set; }
    }
}
