//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgetHub_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationRequests
    {
        public int QuotationRequestID { get; set; }
        public string DistributorName { get; set; }
        public decimal QuotationPrice { get; set; }
        public Nullable<System.DateTime> QuotationDate { get; set; }
        public string Status { get; set; }
    }
}
